### PR TITLE
Support custom Ubuntu AMIs for EKS-managed nodegroups

### LINKED ISSUE #6491: [Help] Unable to create EKS managed nodegroups with custom Ubuntu AMI
```
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: private-eks-cluster
  region: us-east-1
  version: "1.24"

vpc:
  subnets:
    private:
      us-east-1a: 
        id: subnet-xxxxxx
      us-east-1b: 
        id: subnet-xxxxxxx
        
managedNodeGroups:
  - name:  worker
    labels: { nodeType: worker }
    instanceType: t2.xlarge
    desiredCapacity: 2
    ami: "ami-003237eb446483b5"
    privateNetworking: true
    overrideBootstrapCommand: |
      #!/bin/bash
      /etc/eks/bootstrap.sh private-eks-cluster
```

$  eksctl create cluster -f ./cluster.yaml
Error: when using a custom AMI, amiFamily needs to be explicitly set via config file or via --node-ami-family flag

Trying to create a eks cluster using the ubuntu custom AMI from canonical, eksctl is complaining to set amiFamily, but when I add amiFamily then the request fails with the below error. 

```
$ eksctl create cluster -f ./cie-cluster-custom-ubuntu.yaml 
Error: cannot set amiFamily to Ubuntu2004 when using a custom AMI for managed nodes, only AmazonLinux2 is supported
```

### PR DESCRIPTION
**Pull request by TiberiuGC**
### Description

Closes #6491 

There's been plenty community traction for supporting this feature. Users are currently able to create EKS-managed nodes with custom Ubuntu AMIs via various workarounds that bypass `eksctl` validations e.g. https://github.com/eksctl-io/eksctl/issues/6491#issuecomment-1571284046. Before enforcing the users to specify the `AMIFamily` whenever working with a costum AMI (see https://github.com/eksctl-io/eksctl/pull/6243), bypassing the validations was much easier. Thus, in reality, this functionality has been used by community for a long time now. Since no particular issues were reported in the past, we're bringing it back by relaxing the existing validations.

### Checklist
- [x] Added tests that cover your change (if possible)
- [x] Added/modified documentation as required (such as the `README.md`, or the `userdocs` directory)
- [x] Manually tested
- [x] Made sure the title of the PR is a good description that can go into the release notes
- [x] (Core team) Added labels for change area (e.g. `area/nodegroup`) and kind (e.g. `kind/improvement`)

### BONUS POINTS checklist: complete for good vibes and maybe prizes?! :exploding_head:
- [ ] Backfilled missing tests for code in same general area :tada:
- [ ] Refactored something and made the world a better place :star2:

### CODE REVIEW

**Review by cPu1 — APPROVED** [review]

**Comment by bradwatsonaws** [comment]
@TiberiuGC first of all, thank you for relaxing some of the validation requirements in this update! But is there really a need to specify the amiFamily flag when using a custom AMI? Maybe I just don't see the point of it. I am creating Red Hat Enterprise Linux custom AMIs, and there is no supported amiFamily I can pass in for these AMIs. However, I can just say the amiFamily is AmazonLinux2 and the nodegroup is created without any issues. If the unique AMI ID is being passed in, what is the need for an amiFamily value?

**Comment by TiberiuGC** [comment]
> @TiberiuGC first of all, thank you for relaxing some of the validation requirements in this update! But is there really a need to specify the amiFamily flag when using a custom AMI? Maybe I just don't see the point of it. I am creating Red Hat Enterprise Linux custom AMIs, and there is no supported amiFamily I can pass in for these AMIs. However, I can just say the amiFamily is AmazonLinux2 and the nodegroup is created without any issues. If the unique AMI ID is being passed in, what is the need for an amiFamily value?

Hi @bradwatsonaws , that's a valid point. The main reason why we need `amiFamily` to be explicitly set when working with `customAMIs` is because some of the supported families (i.e. AL2 & Ubuntu) require `overrideBootstrapCommand`, whereas others (i.e. Bottlerocket & Windows) don't support it. In your scenario, if your `amiFamily` works just fine with the `overrideBootstrapCommand`, indeed setting it to AL2 in eksctl will not trigger any errors.

One issue that we faced in the past was people using Bottlerocket `customAMIs` but without specifying the `amiFamily`. Therefore they were incorrectly forced to provide an override bootstrap script, instead of being forced to correctly use the [bottlerocket settings](https://github.com/eksctl-io/eksctl/blob/3ac2b24b6819da5f551d43fcb7764d57fa199f7b/examples/20-bottlerocket.yaml#L20C1-L23). This resulted in these bugs https://github.com/eksctl-io/eksctl/issues/6029 and https://github.com/eksctl-io/eksctl/issues/5756.

After introducing the requirement of specifying the `amiFamily`, users started facing the validation that was relaxed in this PR, as they could no longer simply bypass it by not specifying the field. https://github.com/eksctl-io/eksctl/blob/3ac2b24b6819da5f551d43fcb7764d57fa199f7b/pkg/apis/eksctl.io/v1alpha5/validation.go#L1210-L1211
This validation has been in place for a very long time and I can't fully confirm the motivations behind it, or whether there are any limitations in simply allowing any `amiFamily` to be used with EKS managed nodegroups. The reason for relaxing the validation is stated in the PR description.

**Pull request merged**
